# Generated by Django 4.1.3 on 2022-12-05 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0004_alter_fasttrack_cie_alter_fasttrack_attemptnumber_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='courserequest',
            name='sem',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='sem1',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem1',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem1',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem1',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem1',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem2',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem2',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem2',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem2',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem2',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem3',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem3',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem3',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem3',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem3',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem4',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem4',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem4',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem4',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem4',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem5',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem5',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem5',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem5',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem5',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem6',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem6',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem6',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem6',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem6',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem7',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem7',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem7',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem7',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem7',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem8',
            name='CIE',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem8',
            name='GradePoints',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem8',
            name='SEE',
            field=models.CharField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='sem8',
            name='attemptNumber',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sem8',
            name='attendance',
            field=models.TextField(blank=True, null=True),
        ),
    ]
