# Generated by Django 4.1.3 on 2022-12-05 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0005_courserequest_sem_alter_sem1_cie_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('courseName', models.TextField()),
                ('courseCode', models.TextField()),
                ('credit', models.TextField()),
                ('registration', models.TextField()),
                ('attemptNumber', models.TextField(blank=True, null=True)),
                ('attendance', models.TextField(blank=True, null=True)),
                ('CIE', models.TextField(blank=True, null=True)),
                ('SEE', models.CharField(blank=True, max_length=1, null=True)),
                ('GradePoints', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='FastTrack',
        ),
        migrations.DeleteModel(
            name='Sem1',
        ),
        migrations.DeleteModel(
            name='Sem2',
        ),
        migrations.DeleteModel(
            name='Sem3',
        ),
        migrations.DeleteModel(
            name='Sem4',
        ),
        migrations.DeleteModel(
            name='Sem5',
        ),
        migrations.DeleteModel(
            name='Sem6',
        ),
        migrations.DeleteModel(
            name='Sem7',
        ),
        migrations.DeleteModel(
            name='Sem8',
        ),
    ]
