# Generated by Django 4.1.3 on 2022-12-08 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0006_sem_delete_fasttrack_delete_sem1_delete_sem2_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('sem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='student_dashboard.sem')),
            ],
            bases=('student_dashboard.sem',),
        ),
        migrations.CreateModel(
            name='StudentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('date_of_birth', models.DateField()),
                ('permanent_address', models.TextField()),
                ('current_address', models.TextField()),
                ('phone_number', models.CharField(max_length=10)),
                ('blood_group', models.CharField(max_length=3)),
                ('father_name', models.CharField(max_length=200)),
                ('mother_name', models.CharField(max_length=200)),
                ('father_occupation', models.CharField(max_length=200)),
                ('mother_occupation', models.CharField(max_length=200)),
                ('father_phone_number', models.CharField(max_length=10)),
                ('mother_phone_number', models.CharField(max_length=10)),
                ('father_email', models.EmailField(max_length=254)),
                ('mother_email', models.EmailField(max_length=254)),
                ('guardian_name', models.CharField(max_length=200)),
                ('guardian_phone_number', models.CharField(max_length=10)),
                ('guardian_email', models.EmailField(max_length=254)),
                ('class_10th_school', models.CharField(max_length=200)),
                ('class_10th_board', models.CharField(max_length=200)),
                ('class_10th_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_10th_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('class_12th_school', models.CharField(max_length=200)),
                ('class_12th_board', models.CharField(max_length=200)),
                ('class_12th_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_12th_year', models.DecimalField(decimal_places=0, max_digits=4)),
                ('class_Diploma_school', models.CharField(max_length=200)),
                ('class_Diploma_board', models.CharField(max_length=200)),
                ('class_Diploma_percentage', models.DecimalField(decimal_places=2, max_digits=5)),
                ('class_Diploma_year', models.DecimalField(decimal_places=0, max_digits=4)),
            ],
        ),
    ]
