# Generated by Django 4.1.3 on 2022-12-08 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0006_sem_delete_fasttrack_delete_sem1_delete_sem2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='current_sem',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=1, null=True),
        ),
    ]
