# Generated by Django 4.1 on 2022-12-10 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("faculty_dashboard", "0001_initial"),
        ("student_dashboard", "0007_alter_student_current_sem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="proctor_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="faculty_dashboard.faculty",
            ),
        ),
    ]
