# Generated by Django 4.1.3 on 2022-12-08 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0008_alter_student_current_sem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentdetails',
            name='class_Diploma_board',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='class_Diploma_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='class_Diploma_school',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='class_Diploma_year',
            field=models.DecimalField(blank=True, decimal_places=0, max_digits=4, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='father_occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='studentdetails',
            name='mother_occupation',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
