# Generated by Django 4.1 on 2022-12-11 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_dashboard", "0008_alter_student_proctor_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sem",
            name="CIE",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sem",
            name="GradePoints",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sem",
            name="SEE",
            field=models.FloatField(blank=True, max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name="sem",
            name="attemptNumber",
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="sem",
            name="attendance",
            field=models.FloatField(blank=True, null=True),
        ),
    ]
