# Generated by Django 4.1.3 on 2022-12-08 15:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0009_alter_studentdetails_class_diploma_board_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='StudentDetails',
            new_name='StudentDetail',
        ),
    ]
