# Generated by Django 4.1.3 on 2023-01-03 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0009_alter_sem_cie_alter_sem_gradepoints_alter_sem_see_and_more'),
        ('student_dashboard', '0010_rename_studentdetails_studentdetail'),
    ]

    operations = [
    ]
