# Generated by Django 4.1.3 on 2023-01-05 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_dashboard', '0001_initial'),
        ('student_dashboard', '0011_merge_20230103_1836'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fastrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('courseName', models.TextField()),
                ('courseCode', models.TextField()),
                ('credit', models.TextField()),
                ('registration', models.TextField()),
                ('attemptNumber', models.FloatField(blank=True, null=True)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('CIE', models.FloatField(blank=True, null=True)),
                ('SEE', models.FloatField(blank=True, max_length=1, null=True)),
                ('GradePoints', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='student',
            name='proctor_id',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard.faculty'),
        ),
    ]
