# Generated by Django 4.1.3 on 2023-01-05 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_dashboard', '0001_initial'),
        ('student_dashboard', '0012_fastrack_alter_student_proctor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='proctor_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='faculty_dashboard.faculty'),
        ),
    ]
