# Generated by Django 4.1.3 on 2023-01-05 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0013_alter_student_proctor_id'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Fastrack',
        ),
    ]
