# Generated by Django 4.1.3 on 2023-01-05 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0014_delete_fastrack'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fastrack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('USN', models.CharField(max_length=10)),
                ('sem', models.IntegerField()),
                ('courseName', models.TextField()),
                ('courseCode', models.TextField()),
                ('credit', models.TextField()),
                ('registration', models.TextField()),
                ('attemptNumber', models.FloatField(blank=True, null=True)),
                ('attendance', models.FloatField(blank=True, null=True)),
                ('CIE', models.FloatField(blank=True, null=True)),
                ('SEE', models.FloatField(blank=True, max_length=1, null=True)),
                ('GradePoints', models.FloatField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
