# Generated by Django 4.1.3 on 2023-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0015_fastrack'),
    ]

    operations = [
        migrations.AddField(
            model_name='sem',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sem',
            name='is_marks_approved',
            field=models.BooleanField(default=False),
        ),
    ]
