# Generated by Django 4.1.3 on 2023-01-10 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_dashboard', '0016_sem_is_approved_sem_is_marks_approved'),
    ]

    operations = [
        migrations.AddField(
            model_name='fastrack',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentdetail',
            name='isApproved',
            field=models.BooleanField(default=False),
        ),
    ]
