# Generated by Django 4.1 on 2022-11-24 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_auth", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="usn",
            field=models.CharField(max_length=10),
        ),
    ]
