# Generated by Django 4.1.3 on 2022-11-25 07:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student_auth', '0003_user_is_teacher'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='usn',
        ),
    ]
