# Generated by Django 4.1.3 on 2023-01-05 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faculty_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='designation',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
